#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if grep -Fq -- "$needle" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "ERROR: missing $label in $file" >&2
    errors=$((errors + 1))
  fi
}

forbid_text() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if grep -Fq -- "$needle" "$repo_root/$file"; then
    echo "ERROR: forbidden $label in $file" >&2
    errors=$((errors + 1))
  else
    echo "ok: $label"
  fi
}

require_text "shared/references/visual-to-wordpress-implementation.md" "Inspect the actual source visual" "actual visual inspection"
require_text "shared/references/visual-to-wordpress-implementation.md" 'supplied`, `measured`, or `inferred' "visual evidence confidence"
require_text "shared/references/visual-to-wordpress-implementation.md" "ambiguity ledger" "visual ambiguity decision discipline"
require_text "shared/references/visual-to-wordpress-implementation.md" "reusable component contracts" "visual component-system extraction"
require_text "shared/references/visual-to-wordpress-implementation.md" "Handle Image Assets Deliberately" "asset generation workflow"
require_text "shared/references/visual-to-wordpress-implementation.md" "small candidate set" "generated asset convergence"
require_text "shared/references/visual-to-wordpress-implementation.md" "provenance" "asset provenance"
require_text "shared/references/visual-to-wordpress-implementation.md" "wordpress-asset-production.schema.json" "structured asset production receipt"
require_text "shared/references/visual-to-wordpress-implementation.md" "validate-asset-production.mjs" "asset receipt validator routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "Site strategy" "site/theme ownership split"
require_text "shared/references/visual-to-wordpress-implementation.md" "overlay or perceptual diff" "measurable visual comparison"
require_text "shared/references/visual-to-wordpress-implementation.md" "hard-edge geometry deltas above 2 CSS px" "deterministic exact-target investigation threshold"
require_text "shared/references/visual-to-wordpress-implementation.md" "capture fingerprint" "deterministic capture contract"
require_text "shared/references/visual-to-wordpress-implementation.md" "visitor completes the primary task" "visitor workflow proof"
require_text "shared/references/visual-to-wordpress-implementation.md" "author completes the primary editing task" "author workflow proof"
require_text "shared/references/visual-to-wordpress-implementation.md" "mobile proof covers accessible, coherent inferred behavior, not pixel parity" "missing-mobile-design rule"
require_text "shared/references/visual-to-wordpress-implementation.md" "support slot" "single-support collision handling"
require_text "shared/references/visual-to-wordpress-implementation.md" "Figma Source Preflight" "structured Figma source preflight"
require_text "shared/references/visual-to-wordpress-implementation.md" "figma-implement-design" "Figma capability routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "wordpress-visual-proof.schema.json" "structured visual proof receipt"
require_text "shared/references/visual-to-wordpress-implementation.md" "validate-visual-proof.mjs" "visual proof validator routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "required capture, workflow, environment, and asset IDs" "visual proof declared coverage"
require_text "shared/references/visual-to-wordpress-implementation.md" "Material accessibility names the tested browser/assistive-technology task" "visual proof accessibility matrix"
require_text "shared/references/visual-to-wordpress-implementation.md" "token drift or unowned raw values" "visual proof token lineage"
require_text "shared/references/visual-to-wordpress-implementation.md" "observed and fixed evidence under one defect ID" "visual defect reproof lineage"
require_text "shared/references/visual-to-wordpress-implementation.md" "P1/P2 defects cannot be accepted" "non-waivable visual defects"
require_text "shared/schemas/wordpress-visual-proof.schema.json" '"requiredStateCoverage"' "visual state coverage schema"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "exact comparison must bind distinct source and candidate evidence" "distinct exact comparison evidence"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "fixed evidence must differ from observed evidence" "visual reproof fingerprint separation"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "fingerprint does not match evidence bytes" "visual evidence byte verification"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "identity or result does not match linked receipt" "nested asset receipt verification"
require_text "wp-expert/scripts/validate-asset-production.mjs" "at least two scored candidates" "generated asset alternative threshold"
require_text "wp-expert/scripts/validate-asset-production.mjs" "score at least 4" "generated asset quality threshold"
require_text "wp-expert/scripts/validate-asset-production.mjs" "crop target aspect ratio" "generated asset crop-ratio validation"
require_text "wp-expert/scripts/validate-asset-production.mjs" "fingerprint does not match evidence bytes" "asset evidence byte verification"
require_text "shared/references/visual-to-wordpress-implementation.md" "sets the work to \`FAIL\` and reopens implementation" "failed visual proof recovery gate"
require_text "shared/references/visual-to-wordpress-implementation.md" "cannot convert an observed failure into a pass" "observed failure proof-gap prohibition"
require_text "wp-expert/references/visual-parity-regression.md" "Baseline Governance" "visual baseline governance"
require_text "wp-expert/references/visual-parity-regression.md" "WordPress Theme Unit Test Data" "theme content stress fixture"
require_text "wp-expert/references/visual-parity-regression.md" "container queries" "intrinsic responsive architecture"
require_text "wp-expert/references/visual-parity-regression.md" "repo-specific budgets" "measurable frontend budget"
require_text "wp-expert/references/block-theme-architecture.md" "WordPress.org Theme Directory themes must not ship custom blocks" "public theme custom block boundary"
require_text "wp-expert/references/block-theme-architecture.md" "theme switch/deactivation portability" "theme portability proof"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Focus Not Obscured" "WCAG 2.2 focus criterion"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "24x24" "WCAG 2.2 target size criterion"
require_text "wp-quality-reviewer/references/accessibility-review-fix.md" "no automated tool alone determines accessibility" "accessibility human evaluation gate"
require_text "wp-quality-reviewer/references/accessibility-review-fix.md" "authoring experience" "WordPress author accessibility proof"
require_text "wp-expert/references/theme-frontend-performance-quality-gate.md" "Measurable Budget Contract" "theme performance budget contract"
require_text "wp-expert/references/style-guide-theme-translation.md" "CSS And Cascade Governance" "enterprise CSS cascade contract"
require_text "wp-expert/references/style-guide-theme-translation.md" "user Global Styles" "Global Styles precedence"
require_text "shared/references/design-intelligence-routing.md" "Discover the named capability" "design capability discovery"
require_text "shared/references/design-intelligence-routing.md" "frontend-design-taste.md" "frontend taste routing"
require_text "shared/references/frontend-design-taste.md" "Experience dials: expressiveness" "frontend design read"
require_text "shared/references/frontend-design-taste.md" "diagnostic signals, not universal bans" "contextual anti-template judgment"
require_text "shared/references/frontend-design-taste.md" "Never fabricate brands" "frontend truth boundary"
require_text "shared/references/frontend-design-taste.md" "visitor completes the primary task" "frontend visitor workflow proof"
require_text "shared/references/frontend-design-taste.md" "author/operator completes" "frontend author workflow proof"
require_text "shared/references/frontend-design-taste.md" "smallest representative direction artifact" "material direction checkpoint"
require_text "shared/references/frontend-design-taste.md" "not excellent usability by themselves" "visual proof usability boundary"
require_text "wp-expert/references/ux-product-strategy-design-qa.md" "Risk-Tiered Usability Evidence" "risk-tiered usability evidence"
require_text "wp-expert/references/ux-product-strategy-design-qa.md" "never call screenshot parity or an engineer walkthrough proof of excellent UX" "excellent UX evidence boundary"
require_text "wp-site-expert/references/router.md" "frontend-design-taste.md" "site frontend taste route"
require_text "wp-theme-expert/references/router.md" "frontend-design-taste.md" "theme frontend taste route"
require_text "wp-plugin-expert/references/router.md" "ui-ux-pro-for-wordpress.md" "plugin premium UI route"
require_text "wp-plugin-expert/references/router.md" "wordpress-design-system.md" "plugin WordPress design system route"
require_text "wp-plugin-expert/references/router.md" "frontend-design-taste.md" "plugin frontend taste route"
require_text "wp-plugin-expert/SKILL.md" "plugin-owned admin, editor, or customer-facing UI" "plugin direct exact-visual trigger"
require_text "wp-plugin-expert/references/router.md" "visual-to-wordpress-implementation.md" "plugin exact visual route"
require_text "shared/references/worker-execution-discipline.md" "Claim And Evidence Gate" "claim evidence gate"
require_text "shared/references/worker-execution-discipline.md" "Never invent WordPress hooks" "hallucination guard"
require_text "shared/references/worker-execution-discipline.md" "Owner Correction To Learning" "worker learning trigger"
require_text "shared/references/worker-execution-discipline.md" "Failed Visual Evidence Recovery" "worker visual convergence recovery"
require_text "wp-product-orchestrator/SKILL.md" "invoke the self-improvement loop" "PO learning routing"
require_text "wp-product-orchestrator/SKILL.md" "observed in-scope visual defect is failed proof" "PO rejects broken visual proof"
require_text "wp-expert/scripts/fse-design-map.sh" "Visual Region Measurements" "FSE visual measurements"
require_text "wp-expert/scripts/fse-design-map.sh" "Asset Inventory" "FSE asset inventory"
require_text "skill-evals/visual-wordpress-scenarios.md" "Skills loaded" "eval context telemetry"
require_text "skill-evals/visual-wordpress-scenarios.md" "Unavailable Design Capability" "unavailable capability scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Hallucinated WordPress Contract" "hallucination scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Owner Correction Learning" "learning scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Broken Candidate Proof During Implementation" "broken candidate recovery scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "WordPress.org Theme Custom Block Boundary" "theme distribution scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Visual With Custom Block Architecture Risk" "combined visual architecture route scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Enterprise Theme Content And Responsive Stress" "theme stress scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Site Editor Design Promotion" "Site Editor promotion scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Existing Site Screenshot To Editable Page" "site screenshot implementation scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Generic SaaS Composition Without A Target" "greenfield frontend taste scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Preserve Redesign Without Contract Drift" "preserve redesign scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Operational Dashboard Rejects Marketing Taste" "operational UI route boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Motion Proposal Needs A Contract" "motivated motion scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Sparse Brief Cannot Create Proof" "frontend truth boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Polished But Repetitive Candidate" "anti-template composition scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Target Must Not Be Reinterpreted" "exact target taste boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Taste Proof Across Intermediate Widths" "frontend taste proof scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Plugin-Owned Product Surface Routing" "plugin product surface routing scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Excellent UX Requires Outcome Evidence" "excellent UX evidence scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Material Greenfield Direction Checkpoint" "greenfield direction checkpoint scenario"
require_text "shared/references/core-first-site-theme-workflow.md" "get_all_registered()" "live block registry verification"
require_text "shared/references/core-first-site-theme-workflow.md" "activation/license requirements" "plugin block dependency inventory"
require_text "shared/references/core-first-site-theme-workflow.md" 'Treat `core/tabs`, `core/table-of-contents`, `core/form`' "runtime-dependent documented blocks"
require_text "shared/references/core-first-site-theme-workflow.md" 'prefer `core/icon`, `core/breadcrumbs`, `core/accordion`' "core-first block mapping"
require_text "shared/references/core-first-site-theme-workflow.md" "parse_blocks()" "saved block structure proof"
require_text "shared/references/core-first-site-theme-workflow.md" "do_blocks()" "saved block render proof"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_template` or `wp_template_part` records' "Site Editor override precedence"
require_text "shared/references/core-first-site-theme-workflow.md" "Promote Intentional Editor Changes" "Site Editor database-to-file lifecycle"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_global_styles`' "Global Styles database precedence"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_navigation`' "Navigation database dependency"
require_text "shared/references/core-first-site-theme-workflow.md" 'templates/{slug}.html' "Site Editor template artifact mapping"
require_text "shared/references/core-first-site-theme-workflow.md" 'Resolve nonportable `ref` and numeric IDs' "Site Editor reference migration"
require_text "shared/references/core-first-site-theme-workflow.md" "Production-Ready Evidence" "Site Editor production evidence gate"
require_text "shared/references/core-first-site-theme-workflow.md" "release artifact" "packaged clean-install proof"
require_text "skill-evals/core-first-site-theme-scenarios.md" "Documented block absent" "runtime block availability scenario"
require_text "wp-site-expert/references/router.md" "core-first-site-theme-workflow.md" "site core-first routing"
require_text "wp-theme-expert/references/router.md" "core-first-site-theme-workflow.md" "theme core-first routing"
require_text "wp-theme-expert/references/router.md" "block-editor-page-composition.md" "theme block composition routing"
require_text "wp-site-expert/references/router.md" "block-editor-page-composition.md" "site block composition routing"
require_text "wp-site-expert/SKILL.md" "With a screenshot, Figma frame, image, mockup, or selected direction" "site direct visual trigger"
require_text "shared/references/block-editor-page-composition.md" "Frontend resemblance is not completion" "editor-native completion contract"
require_text "shared/references/block-editor-page-composition.md" "registered Core and plugin block types" "core plugin block inventory"
require_text "shared/references/block-editor-page-composition.md" "Patterns solve repeatable composition; styles solve appearance; variations solve insertion presets" "pattern style variation boundary"
require_text "shared/references/block-editor-page-composition.md" "A Page template provides structure and renders Post Content" "page ownership contract"
require_text "shared/references/block-editor-page-composition.md" "A Single Post template owns post title" "post ownership contract"
require_text "shared/references/block-editor-page-composition.md" "page-ID selectors, DOM-position selectors, pseudo-content" "frontend CSS patch prohibition"
require_text "shared/references/block-editor-page-composition.md" "intended non-technical role" "nontechnical author proof"
require_text "shared/references/block-editor-page-composition.md" "Remove redundant single-child Group wrappers" "editor hierarchy complexity guard"
require_text "shared/references/block-editor-page-composition.md" "collapsed top-level List View" "observable List View author proof"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "Plugin block inventory" "plugin block scenario"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "Repeated proof cards" "CSS patch regression scenario"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "WYSIWYG proof" "WYSIWYG author scenario"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "no CSS/code knowledge is required" "source-blind author workflow proof"
require_text "wp-expert/scripts/fse-design-map.sh" "Component Contracts" "FSE component contract fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Golden Workflows" "FSE golden workflow fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Capture fingerprint" "FSE deterministic proof fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Structured visual proof receipt path" "FSE structured visual receipt field"
require_text "wp-expert/references/interactivity-api-frontend.md" "Client-Side Navigation" "Interactivity API client navigation contract"
require_text "wp-expert/references/interactivity-api-frontend.md" "duplicate listeners" "Interactivity lifecycle cleanup"
require_text "wp-expert/references/interactivity-api-frontend.md" "Back, Forward" "Interactivity history proof"
require_text "wp-expert/references/interactivity-api-frontend.md" "no-JS" "Interactivity progressive enhancement proof"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Consistent Help" "WCAG 2.2 consistent help"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Redundant Entry" "WCAG 2.2 redundant entry"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "actual supported browser/assistive-technology pair" "named assistive technology proof"
forbid_text "wp-expert/references/ui-ux-pro-for-wordpress.md" "150-300ms" "universal admin motion timing removed"
forbid_text "wp-expert/references/ux-product-strategy-design-qa.md" "150-300ms" "universal product motion timing removed"
require_text "shared/references/frontend-design-taste.md" "accountability read" "enterprise taste accountability"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Plugin Customer Surface" "plugin exact visual scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Structured Figma Source" "Figma source scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Visual Receipt Rejects Broken Candidate" "visual receipt negative scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Interactive Block Client Navigation" "interactive navigation scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Multi-Step WCAG Flow" "WCAG flow scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Multi-Surface Coverage Cannot Be Inferred" "per-surface proof scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Vague Evidence Cannot Pass" "concrete evidence scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Generated Asset Receipt Rejects A Near Miss" "asset receipt scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Elevated Design Token Drift" "design token lineage scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Fixed Defect Requires Reproof" "visual defect lineage scenario"

node "$repo_root/wp-expert/scripts/validate-visual-proof.mjs" --self-test
echo "ok: visual proof validator"
node "$repo_root/wp-expert/scripts/validate-asset-production.mjs" --self-test
echo "ok: asset production validator"

if [ "$errors" -gt 0 ]; then
  echo "visual WordPress behavior audit failed: $errors issue(s)" >&2
  exit 1
fi

echo "visual WordPress behavior audit passed"
