#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
errors=0

require_text() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if grep -Fq -- "$needle" "$repo_root/$file"; then
    echo "ok: $label"
  else
    echo "ERROR: missing $label in $file" >&2
    errors=$((errors + 1))
  fi
}

forbid_text() {
  local file="$1"
  local needle="$2"
  local label="$3"
  if grep -Fq -- "$needle" "$repo_root/$file"; then
    echo "ERROR: forbidden $label in $file" >&2
    errors=$((errors + 1))
  else
    echo "ok: $label"
  fi
}

require_text "shared/references/visual-to-wordpress-implementation.md" "Inspect the actual source visual" "actual visual inspection"
require_text "shared/references/visual-to-wordpress-implementation.md" 'supplied`, `measured`, or `inferred' "visual evidence confidence"
require_text "shared/references/visual-to-wordpress-implementation.md" "ambiguity ledger" "visual ambiguity decision discipline"
require_text "shared/references/visual-to-wordpress-implementation.md" "reusable component contracts" "visual component-system extraction"
require_text "shared/references/visual-to-wordpress-implementation.md" "Handle Image Assets Deliberately" "asset generation workflow"
require_text "shared/references/visual-to-wordpress-implementation.md" "small candidate set" "generated asset convergence"
require_text "shared/references/visual-to-wordpress-implementation.md" "provenance" "asset provenance"
require_text "shared/references/visual-to-wordpress-implementation.md" "wordpress-asset-production.schema.json" "structured asset production receipt"
require_text "shared/references/visual-to-wordpress-implementation.md" "validate-asset-production.mjs" "asset receipt validator routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "Site strategy" "site/theme ownership split"
require_text "shared/references/visual-to-wordpress-implementation.md" "overlay or perceptual diff" "measurable visual comparison"
require_text "shared/references/visual-to-wordpress-implementation.md" "hard-edge geometry deltas above 2 CSS px" "deterministic exact-target investigation threshold"
require_text "shared/references/visual-to-wordpress-implementation.md" "capture fingerprint" "deterministic capture contract"
require_text "shared/references/visual-to-wordpress-implementation.md" "visitor completes the primary task" "visitor workflow proof"
require_text "shared/references/visual-to-wordpress-implementation.md" "author completes the primary editing task" "author workflow proof"
require_text "shared/references/visual-to-wordpress-implementation.md" "mobile proof covers accessible, coherent inferred behavior, not pixel parity" "missing-mobile-design rule"
require_text "shared/references/visual-to-wordpress-implementation.md" "support slot" "single-support collision handling"
require_text "shared/references/visual-to-wordpress-implementation.md" "Figma Source Preflight" "structured Figma source preflight"
require_text "shared/references/visual-to-wordpress-implementation.md" "figma-implement-design" "Figma capability routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "wordpress-visual-proof.schema.json" "structured visual proof receipt"
require_text "shared/references/visual-to-wordpress-implementation.md" "validate-visual-proof.mjs" "visual proof validator routing"
require_text "shared/references/visual-to-wordpress-implementation.md" "required capture, workflow, environment, and asset IDs" "visual proof declared coverage"
require_text "shared/references/visual-to-wordpress-implementation.md" "Material accessibility names the tested browser/assistive-technology task" "visual proof accessibility matrix"
require_text "shared/references/visual-to-wordpress-implementation.md" "token drift or unowned raw values" "visual proof token lineage"
require_text "shared/references/visual-to-wordpress-implementation.md" "observed and fixed evidence under one defect ID" "visual defect reproof lineage"
require_text "shared/references/visual-to-wordpress-implementation.md" "P1/P2 defects cannot be accepted" "non-waivable visual defects"
require_text "shared/schemas/wordpress-visual-proof.schema.json" '"requiredStateCoverage"' "visual state coverage schema"
require_text "shared/schemas/wordpress-visual-proof.schema.json" '"tokenImplementation"' "structured token implementation schema"
require_text "shared/schemas/wordpress-visual-proof.schema.json" '"affectedCaptureIds"' "visual defect affected-capture schema"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "exact comparison must bind distinct source and candidate evidence" "distinct exact comparison evidence"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "required captures must bind distinct candidate artifact fingerprints" "distinct per-capture candidate evidence"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "scope surface lacks a required workflow" "per-surface workflow proof"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "lacks a required capture for environment" "per-surface environment proof"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "must bind a rendered layer" "rendered token lineage proof"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "fixed evidence must bind an affected passing capture or workflow rerun" "affected defect reproof binding"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "fixed evidence must differ from observed evidence" "visual reproof fingerprint separation"
require_text "wp-expert/scripts/proof-evidence-files.mjs" "fingerprint does not match evidence bytes" "shared evidence byte verification"
require_text "wp-expert/scripts/proof-evidence-files.mjs" "must be relative to the declared evidence root" "visual evidence path containment"
require_text "wp-expert/scripts/proof-evidence-files.mjs" "100 MiB verification limit" "visual evidence size bound"
require_text "wp-expert/scripts/validate-visual-proof.mjs" "identity or result does not match linked receipt" "nested asset receipt verification"
require_text "wp-expert/scripts/validate-asset-production.mjs" "at least two scored candidates" "generated asset alternative threshold"
require_text "wp-expert/scripts/validate-asset-production.mjs" "score at least 4" "generated asset quality threshold"
require_text "wp-expert/scripts/validate-asset-production.mjs" "crop target aspect ratio" "generated asset crop-ratio validation"
require_text "wp-expert/scripts/validate-asset-production.mjs" "verifyProofEvidenceFiles" "asset evidence shared byte verification"
require_text "shared/references/visual-to-wordpress-implementation.md" "sets the work to \`FAIL\` and reopens implementation" "failed visual proof recovery gate"
require_text "shared/references/visual-to-wordpress-implementation.md" "cannot convert an observed failure into a pass" "observed failure proof-gap prohibition"
require_text "wp-expert/references/visual-parity-regression.md" "Baseline Governance" "visual baseline governance"
require_text "wp-expert/references/visual-parity-regression.md" "WordPress Theme Unit Test Data" "theme content stress fixture"
require_text "wp-expert/references/visual-parity-regression.md" "container queries" "intrinsic responsive architecture"
require_text "wp-expert/references/visual-parity-regression.md" "repo-specific budgets" "measurable frontend budget"
require_text "wp-expert/references/visual-parity-regression.md" "Design-System Integrity And Proof Provenance" "design-system integrity and proof provenance"
require_text "wp-expert/references/visual-parity-regression.md" "supported, best-effort, and unsupported" "named browser support statuses"
require_text "wp-expert/references/visual-parity-regression.md" "source owner" "proof provenance ownership"
require_text "wp-expert/references/block-theme-architecture.md" "WordPress.org Theme Directory themes must not ship custom blocks" "public theme custom block boundary"
require_text "wp-expert/references/block-theme-architecture.md" "theme switch/deactivation portability" "theme portability proof"
require_text "wp-expert/references/wordpress-design-system.md" "@wordpress/ui" "current WordPress Design System package transition"
require_text "wp-expert/references/wordpress-design-system.md" "@wordpress/theme" "WordPress Design System theme package"
require_text "wp-expert/references/wordpress-design-system.md" "get_components" "Design System MCP component source"
require_text "wp-expert/references/wordpress-design-system.md" "use-recommended-components" "maintained component recommendation source"
require_text "wp-expert/references/wordpress-design-system.md" "componentStatus" "Storybook component status source"
require_text "wp-expert/references/wordpress-design-system.md" "--wpds-*" "Design System token family"
require_text "wp-expert/references/wordpress-design-system.md" "Document And Overlay Setup" "document-specific component setup"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Focus Not Obscured" "WCAG 2.2 focus criterion"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "24x24" "WCAG 2.2 target size criterion"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Focus Appearance" "WCAG focus appearance criterion"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Error Prevention" "high-consequence error prevention criterion"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Direction, Locale, And Color-Scheme Contract" "global direction and mode contract"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "dir=\"rtl\"" "explicit RTL document direction"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "translation ownership, supported locales, fallback behavior" "translation lifecycle contract"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "semantic token pairs" "semantic color scheme tokens"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" 'color-scheme`/`prefers-color-scheme' "color scheme preference implementation"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Adaptive Enterprise Matrix" "adaptive enterprise matrix"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Browser And Assistive-Technology Support Matrix" "browser and assistive technology support contract"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "no theme flash" "no flash mode proof"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Not applicable - reason" "adaptive dimension disposition"
require_text "shared/references/interaction-and-form-resilience.md" "Native And WordPress-First Boundary" "native interaction boundary"
require_text "shared/references/interaction-and-form-resilience.md" "Pattern Contracts" "custom interaction pattern contract"
require_text "shared/references/interaction-and-form-resilience.md" "Enterprise Mutation And Recovery Contract" "enterprise mutation recovery contract"
require_text "shared/references/interaction-and-form-resilience.md" "server-side idempotency" "retry idempotency contract"
require_text "shared/references/interaction-and-form-resilience.md" "stale data" "concurrent editing conflict contract"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "interaction-and-form-resilience.md" "interaction resilience support route"
require_text "wp-quality-reviewer/references/accessibility-review-fix.md" "no automated tool alone determines accessibility" "accessibility human evaluation gate"
require_text "wp-quality-reviewer/references/accessibility-review-fix.md" "authoring experience" "WordPress author accessibility proof"
require_text "wp-expert/references/theme-frontend-performance-quality-gate.md" "Measurable Budget Contract" "theme performance budget contract"
require_text "wp-expert/references/style-guide-theme-translation.md" "CSS And Cascade Governance" "enterprise CSS cascade contract"
require_text "wp-expert/references/style-guide-theme-translation.md" "user Global Styles" "Global Styles precedence"
require_text "shared/references/tailwind-informed-frontend-engineering.md" "Tailwind is an implementation vocabulary, not a visual direction" "Tailwind design-boundary contract"
require_text "shared/references/tailwind-informed-frontend-engineering.md" "Do not globally inject Preflight" "Tailwind Preflight WordPress boundary"
require_text "shared/references/tailwind-informed-frontend-engineering.md" "Never construct class names from runtime or user-controlled data" "Tailwind class-discovery safety"
require_text "shared/references/tailwind-informed-frontend-engineering.md" "v3 or v4" "Tailwind version verification"
require_text "wp-plugin-expert/references/router.md" "tailwind-informed-frontend-engineering.md" "plugin Tailwind route"
require_text "wp-theme-expert/references/router.md" "tailwind-informed-frontend-engineering.md" "theme Tailwind route"
require_text "wp-site-expert/references/router.md" "tailwind-informed-frontend-engineering.md" "site Tailwind route"
require_text "shared/references/design-intelligence-routing.md" "Discover the named capability" "design capability discovery"
require_text "shared/references/design-intelligence-routing.md" "Source-Visual Intent Gate" "source visual intent routing"
require_text "wp-expert/references/ux-product-strategy-design-qa.md" "A supplied visual is evidence, not automatically the build target" "UX visual intent alignment"
forbid_text "wp-expert/references/ux-product-strategy-design-qa.md" "treat it as the visual source of truth unless" "unclassified screenshot authority"
require_text "shared/references/design-intelligence-routing.md" "Design Understanding Readiness" "image design understanding readiness"
require_text "shared/references/design-intelligence-routing.md" "Redesign Growth Gate" "redesign growth direction gate"
require_text "shared/references/design-intelligence-routing.md" 'Never call a tactic or redesign `proven` without applicable experiment or outcome evidence' "redesign evidence boundary"
require_text "shared/references/design-intelligence-routing.md" "produce the visual direction artifact instead of substituting a prose moodboard" "image design visual artifact output"
require_text "shared/references/visual-to-wordpress-implementation.md" "exact target identity" "selected target identity"
require_text "shared/references/design-intelligence-routing.md" "frontend-design-taste.md" "frontend taste routing"
require_text "shared/references/design-intelligence-routing.md" "emerging-interface-design-contract.md" "emerging interface routing"
require_text "shared/references/frontend-design-taste.md" "Experience dials: expressiveness" "frontend design read"
require_text "shared/references/frontend-design-taste.md" "diagnostic signals, not universal bans" "contextual anti-template judgment"
require_text "shared/references/frontend-design-taste.md" "Never fabricate brands" "frontend truth boundary"
require_text "shared/references/frontend-design-taste.md" "visitor completes the primary task" "frontend visitor workflow proof"
require_text "shared/references/frontend-design-taste.md" "author/operator completes" "frontend author workflow proof"
require_text "shared/references/frontend-design-taste.md" "smallest representative direction artifact" "material direction checkpoint"
require_text "shared/references/frontend-design-taste.md" "not excellent usability by themselves" "visual proof usability boundary"
require_text "shared/references/frontend-design-taste.md" "year label is not a visual specification" "trend label is not design authority"
require_text "shared/references/wordpress-typography-system.md" "Start With Content And Runtime Facts" "typography content-first preflight"
require_text "shared/references/wordpress-typography-system.md" '45-75ch` is a useful starting range' "typography measure heuristic boundary"
require_text "shared/references/wordpress-typography-system.md" "Apply heading letter-spacing only as a small optical correction" "typography tracking restraint"
require_text "shared/references/wordpress-typography-system.md" "theme.json" "typography WordPress token ownership"
require_text "shared/references/wordpress-typography-system.md" "editor/frontend parity" "typography author parity proof"
require_text "shared/references/wordpress-typography-system.md" "all four overrides together" "typography WCAG spacing proof"
require_text "shared/references/emerging-interface-design-contract.md" "Trend Adoption Gate" "trend adoption classification"
require_text "shared/references/emerging-interface-design-contract.md" "without coercive rewards" "gamification dark-pattern boundary"
require_text "shared/references/emerging-interface-design-contract.md" "AI And Adaptive Experience" "governed adaptive AI design"
require_text "shared/references/emerging-interface-design-contract.md" "idempotent, tenant/site-isolated, conflict-aware" "AI automatic-action boundary"
require_text "shared/references/emerging-interface-design-contract.md" "Voice And Multimodal Input" "voice equivalent-path design"
require_text "shared/references/emerging-interface-design-contract.md" "Typography And Dynamic Text" "typography performance contract"
require_text "shared/references/emerging-interface-design-contract.md" "Immersive Media And Guided Motion" "immersive fallback contract"
require_text "wp-expert/references/ui-ux-pro-for-wordpress.md" "queued/streaming, paused/cancelled, stale/offline/reconnecting" "extended asynchronous state coverage"
require_text "wp-expert/references/ux-product-strategy-design-qa.md" "Risk-Tiered Usability Evidence" "risk-tiered usability evidence"
require_text "wp-expert/references/ux-product-strategy-design-qa.md" "never call screenshot parity or an engineer walkthrough proof of excellent UX" "excellent UX evidence boundary"
require_text "wp-site-expert/references/router.md" "frontend-design-taste.md" "site frontend taste route"
require_text "wp-theme-expert/references/router.md" "frontend-design-taste.md" "theme frontend taste route"
require_text "wp-site-expert/references/router.md" "emerging-interface-design-contract.md" "site emerging interface route"
require_text "wp-theme-expert/references/router.md" "emerging-interface-design-contract.md" "theme emerging interface route"
require_text "wp-plugin-expert/references/router.md" "ui-ux-pro-for-wordpress.md" "plugin premium UI route"
require_text "wp-plugin-expert/references/router.md" "wordpress-design-system.md" "plugin WordPress design system route"
require_text "wp-plugin-expert/references/router.md" "frontend-design-taste.md" "plugin frontend taste route"
require_text "wp-plugin-expert/references/router.md" "emerging-interface-design-contract.md" "plugin emerging interface route"
require_text "wp-site-expert/references/router.md" "wordpress-typography-system.md" "site typography system route"
require_text "wp-theme-expert/references/router.md" "wordpress-typography-system.md" "theme typography system route"
require_text "wp-expert/references/plugin-product-architecture.md" "Product Admin Shell Pattern" "plugin admin header shell"
require_text "wp-expert/references/plugin-product-architecture.md" "aria-current=\"page\"" "plugin admin route semantics"
require_text "skill-evals/plugin-admin-header-scenarios.md" "Two-tier product-admin header" "plugin admin header scenario"
require_text "skill-evals/plugin-admin-header-scenarios.md" "Header state and proof" "plugin admin header proof scenario"
require_text "wp-plugin-expert/SKILL.md" "selected implementation target" "plugin direct exact-visual trigger"
require_text "wp-plugin-expert/references/router.md" "visual-to-wordpress-implementation.md" "plugin exact visual route"
require_text "shared/references/worker-execution-discipline.md" "Claim And Evidence Gate" "claim evidence gate"
require_text "shared/references/worker-execution-discipline.md" "Never invent WordPress hooks" "hallucination guard"
require_text "shared/references/worker-execution-discipline.md" "Owner Correction To Learning" "worker learning trigger"
require_text "shared/references/worker-execution-discipline.md" "Failed Visual Evidence Recovery" "worker visual convergence recovery"
require_text "wp-product-orchestrator/SKILL.md" "invoke the self-improvement loop" "PO learning routing"
require_text "wp-product-orchestrator/SKILL.md" "Observed defects fail proof" "PO rejects broken visual proof"
require_text "wp-expert/scripts/fse-design-map.sh" "Visual Region Measurements" "FSE visual measurements"
require_text "wp-expert/scripts/fse-design-map.sh" "Asset Inventory" "FSE asset inventory"
require_text "skill-evals/visual-wordpress-scenarios.md" "Skills loaded" "eval context telemetry"
require_text "skill-evals/visual-wordpress-scenarios.md" "Unavailable Design Capability" "unavailable capability scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Hallucinated WordPress Contract" "hallucination scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Owner Correction Learning" "learning scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Broken Candidate Proof During Implementation" "broken candidate recovery scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "WordPress.org Theme Custom Block Boundary" "theme distribution scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Visual With Custom Block Architecture Risk" "combined visual architecture route scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Trend Pile-On Is Not A Direction" "trend adoption scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Governed Adaptive AI Dashboard" "adaptive AI scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Kinetic Variable Typography" "kinetic typography scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Voice Workflow Requires An Equivalent Path" "voice interface scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Immersive Product Story With Enterprise Constraints" "immersive media scenario"
require_text "skill-evals/emerging-interface-design-scenarios.md" "Enterprise Overview Before Selective Depth" "enterprise progressive depth scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Enterprise Theme Content And Responsive Stress" "theme stress scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Site Editor Design Promotion" "Site Editor promotion scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Existing Site Screenshot To Editable Page" "site screenshot implementation scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Generic SaaS Composition Without A Target" "greenfield frontend taste scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Preserve Redesign Without Contract Drift" "preserve redesign scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Operational Dashboard Rejects Marketing Taste" "operational UI route boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Motion Proposal Needs A Contract" "motivated motion scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Sparse Brief Cannot Create Proof" "frontend truth boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Polished But Repetitive Candidate" "anti-template composition scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Target Must Not Be Reinterpreted" "exact target taste boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Taste Proof Across Intermediate Widths" "frontend taste proof scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Plugin-Owned Product Surface Routing" "plugin product surface routing scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Excellent UX Requires Outcome Evidence" "excellent UX evidence scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Material Greenfield Direction Checkpoint" "greenfield direction checkpoint scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Inspiration Image Requires Direction Before Build" "inspiration image direction scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Ambiguous Improve Request Audits First" "ambiguous image audit scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Growth-Led Redesign Before Image Generation" "growth-led redesign scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Cropped Reference Cannot Prove A System" "cropped image evidence scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Existing Design Language Extension" "design language extension scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Globalized And Adaptive Interface" "globalized adaptive interface scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "WordPress Design System Package Transition" "Design System package transition scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Custom Widget Interaction Contract" "custom interaction semantics scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Enterprise Form Recovery" "enterprise form recovery scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Browser And Assistive Technology Matrix" "browser support matrix scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Token Integrity And Proof Provenance" "token and proof provenance scenario"
require_text "shared/references/core-first-site-theme-workflow.md" "get_all_registered()" "live block registry verification"
require_text "shared/references/core-first-site-theme-workflow.md" "activation/license requirements" "plugin block dependency inventory"
require_text "shared/references/core-first-site-theme-workflow.md" 'Treat `core/tabs`, `core/table-of-contents`, `core/form`' "runtime-dependent documented blocks"
require_text "shared/references/core-first-site-theme-workflow.md" 'prefer `core/icon`, `core/breadcrumbs`, `core/accordion`' "core-first block mapping"
require_text "shared/references/core-first-site-theme-workflow.md" "parse_blocks()" "saved block structure proof"
require_text "shared/references/core-first-site-theme-workflow.md" "do_blocks()" "saved block render proof"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_template` or `wp_template_part` records' "Site Editor override precedence"
require_text "shared/references/core-first-site-theme-workflow.md" "Promote Intentional Editor Changes" "Site Editor database-to-file lifecycle"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_global_styles`' "Global Styles database precedence"
require_text "shared/references/core-first-site-theme-workflow.md" '`wp_navigation`' "Navigation database dependency"
require_text "shared/references/core-first-site-theme-workflow.md" 'templates/{slug}.html' "Site Editor template artifact mapping"
require_text "shared/references/core-first-site-theme-workflow.md" 'Resolve nonportable `ref` and numeric IDs' "Site Editor reference migration"
require_text "shared/references/core-first-site-theme-workflow.md" "Production-Ready Evidence" "Site Editor production evidence gate"
require_text "shared/references/core-first-site-theme-workflow.md" "release artifact" "packaged clean-install proof"
require_text "skill-evals/core-first-site-theme-scenarios.md" "Documented block absent" "runtime block availability scenario"
require_text "wp-site-expert/references/router.md" "core-first-site-theme-workflow.md" "site core-first routing"
require_text "wp-theme-expert/references/router.md" "core-first-site-theme-workflow.md" "theme core-first routing"
require_text "wp-theme-expert/references/router.md" "block-editor-page-composition.md" "theme block composition routing"
require_text "wp-site-expert/references/router.md" "block-editor-page-composition.md" "site block composition routing"
require_text "wp-site-expert/SKILL.md" "selected implementation target" "site direct visual trigger"
require_text "shared/references/block-editor-page-composition.md" "Frontend resemblance is not completion" "editor-native completion contract"
require_text "shared/references/block-editor-page-composition.md" "registered Core and plugin block types" "core plugin block inventory"
require_text "shared/references/block-editor-page-composition.md" "Patterns solve repeatable composition; styles solve appearance; variations solve insertion presets" "pattern style variation boundary"
require_text "shared/references/block-editor-page-composition.md" "A Page template provides structure and renders Post Content" "page ownership contract"
require_text "shared/references/block-editor-page-composition.md" "A Single Post template owns post title" "post ownership contract"
require_text "shared/references/block-editor-page-composition.md" "page-ID selectors, DOM-position selectors, pseudo-content" "frontend CSS patch prohibition"
require_text "shared/references/block-editor-page-composition.md" "intended non-technical role" "nontechnical author proof"
require_text "shared/references/block-editor-page-composition.md" "Remove redundant single-child Group wrappers" "editor hierarchy complexity guard"
require_text "shared/references/block-editor-page-composition.md" "collapsed top-level List View" "observable List View author proof"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "Plugin block inventory" "plugin block scenario"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "Repeated proof cards" "CSS patch regression scenario"
require_text "skill-evals/block-editor-page-composition-scenarios.md" "WYSIWYG proof" "WYSIWYG author scenario"
require_text "behavior-validator/references/wordpress-behavior-contract.md" "no CSS/code knowledge is required" "source-blind author workflow proof"
require_text "wp-expert/scripts/fse-design-map.sh" "Component Contracts" "FSE component contract fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Golden Workflows" "FSE golden workflow fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Capture fingerprint" "FSE deterministic proof fields"
require_text "wp-expert/scripts/fse-design-map.sh" "Structured visual proof receipt path" "FSE structured visual receipt field"
require_text "wp-expert/references/interactivity-api-frontend.md" "Client-Side Navigation" "Interactivity API client navigation contract"
require_text "wp-expert/references/interactivity-api-frontend.md" "duplicate listeners" "Interactivity lifecycle cleanup"
require_text "wp-expert/references/interactivity-api-frontend.md" "Back, Forward" "Interactivity history proof"
require_text "wp-expert/references/interactivity-api-frontend.md" "no-JS" "Interactivity progressive enhancement proof"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Consistent Help" "WCAG 2.2 consistent help"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "Redundant Entry" "WCAG 2.2 redundant entry"
require_text "wp-expert/references/accessibility-i18n-global-readiness.md" "actual supported browser/assistive-technology pair" "named assistive technology proof"
forbid_text "wp-expert/references/ui-ux-pro-for-wordpress.md" "150-300ms" "universal admin motion timing removed"
forbid_text "wp-expert/references/ux-product-strategy-design-qa.md" "150-300ms" "universal product motion timing removed"
require_text "shared/references/frontend-design-taste.md" "accountability read" "enterprise taste accountability"
require_text "skill-evals/visual-wordpress-scenarios.md" "Exact Plugin Customer Surface" "plugin exact visual scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Structured Figma Source" "Figma source scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Visual Receipt Rejects Broken Candidate" "visual receipt negative scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Interactive Block Client Navigation" "interactive navigation scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Multi-Step WCAG Flow" "WCAG flow scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Multi-Surface Coverage Cannot Be Inferred" "per-surface proof scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Vague Evidence Cannot Pass" "concrete evidence scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Generated Asset Receipt Rejects A Near Miss" "asset receipt scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Elevated Design Token Drift" "design token lineage scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Fixed Defect Requires Reproof" "visual defect lineage scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Existing Tailwind Surface Must Preserve WordPress Ownership" "Tailwind WordPress boundary scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Editable WordPress Typography System" "WordPress typography system scenario"
require_text "shared/references/spatial-layout-and-alignment-system.md" "related gap < group gap < section gap" "semantic spatial hierarchy"
require_text "shared/references/spatial-layout-and-alignment-system.md" "4/8-pixel grid is fallback, not proof" "mechanical spacing-scale guard"
require_text "shared/references/spatial-layout-and-alignment-system.md" "inspect both geometries before changing the child" "parent stretch diagnosis"
require_text "shared/references/spatial-layout-and-alignment-system.md" "implementer cannot be sole evaluator" "independent spatial evaluation"
require_text "shared/references/spatial-layout-and-alignment-system.md" "retrieve one matching official" "targeted modern-web retrieval"
require_text "shared/references/spatial-layout-and-alignment-system.md" 'selected exact, directional, or inspiration target is at least `material`' "selected-target spatial risk floor"
require_text "shared/references/spatial-layout-and-alignment-system.md" 'Incomplete proof is `blocked`/`FAIL`' "spatial pass proof-gap prohibition"
require_text "shared/references/spatial-layout-and-alignment-system.md" "After two failed cycles, reopen" "spatial repair-cycle stopping rule"
require_text "shared/references/visual-to-wordpress-implementation.md" "validated spatial receipt" "visual proof spatial receipt link"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"hierarchyId"' "spatial hierarchy schema"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"independent"' "independent evaluator schema"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"implementedBy"' "spatial implementer identity schema"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"parentLayoutRisk"' "parent layout risk schema"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"relationshipValues"' "measured spatial hierarchy schema"
require_text "shared/schemas/wordpress-spatial-proof.schema.json" '"failedCycles"' "spatial repair cycle schema"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "cannot use derived acceptance geometry for an exact target" "exact spatial authority enforcement"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "result disagrees with its expected and actual values" "spatial false-pass enforcement"
require_text "wp-expert/scripts/spatial-proof-contract.mjs" "requires a numeric expected value" "typed spatial comparator"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "must equal the declared semantic token value and unit" "spatial token-value binding"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "acceptance tolerance cannot exceed 2 CSS pixels" "spatial tolerance bound"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "passing selected-target environment lacks an alignment measurement" "per-environment alignment proof"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "passing selected-target environment lacks a parent_layout diagnostic" "per-environment parent proof"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "passing selected-target environment lacks hierarchy measurement" "per-environment hierarchy proof"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "passing selected-target environment lacks anchor measurement" "per-environment anchor proof"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "kind does not match the declared anchor type" "anchor type binding"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "lacks acceptance geometry" "selected-target acceptance geometry"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "subject must exactly match" "anchor exact-subject binding"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "alignmentMode does not match" "anchor mode binding"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "edge does not match logical anchor" "logical edge binding"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "selected visual target requires responsive spatial proof" "responsive downgrade rejection"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "selected visual target requires material or brand-critical spatial risk" "risk downgrade rejection"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "parent layout risk requires a parent_layout diagnostic measurement" "parent layout receipt enforcement"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "selected visual target requires parent layout risk inspection" "selected-target parent inspection"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "selected visual target requires at least one measured spacing hierarchy" "selected-target hierarchy enforcement"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "two failed repair cycles require reopening the spatial contract" "repair cycle validator enforcement"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "must be relative to the declared evidence root" "spatial evidence path containment"
require_text "wp-expert/scripts/validate-spatial-proof.mjs" "100 MiB verification limit" "spatial evidence size bound"
require_text "wp-expert/scripts/capture-spatial-measurements.mjs" "parent_layout" "parent layout browser capture"
require_text "wp-expert/scripts/capture-spatial-measurements.mjs" "Playwright is unavailable" "optional Playwright dependency boundary"
require_text "wp-expert/scripts/capture-spatial-measurements.mjs" "url must not contain embedded credentials" "browser capture credential guard"
require_text "wp-expert/scripts/capture-spatial-measurements.mjs" '"edge_alignment"' "capture receipt kind alignment"
require_text "wp-expert/scripts/spatial-proof-contract.mjs" '"baseline_alignment"' "shared spatial kind contract"
require_text "wp-expert/scripts/spatial-proof-contract.mjs" '"relationship"' "shared relationship capture contract"
require_text "wp-expert/scripts/capture-spatial-measurements.mjs" "inline_zero_size_baseline_probe" "baseline probe capture"
require_text "wp-plugin-expert/references/router.md" "spatial-layout-and-alignment-system.md" "plugin spatial layout route"
require_text "wp-theme-expert/references/router.md" "spatial-layout-and-alignment-system.md" "theme spatial layout route"
require_text "wp-site-expert/references/router.md" "spatial-layout-and-alignment-system.md" "site spatial layout route"
require_text "skill-evals/visual-wordpress-scenarios.md" "Parent Stretch Is Not Child Padding" "parent stretch regression scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Spatial Hierarchy Is Not A Mechanical Grid" "spatial hierarchy regression scenario"
require_text "skill-evals/visual-wordpress-scenarios.md" "Independent Spatial Proof Rejects A Polished Near Miss" "independent spatial proof scenario"

node "$repo_root/wp-expert/scripts/validate-visual-proof.mjs" --self-test
echo "ok: visual proof validator"
node "$repo_root/wp-expert/scripts/validate-asset-production.mjs" --self-test
echo "ok: asset production validator"
node "$repo_root/wp-expert/scripts/validate-spatial-proof.mjs" --self-test
echo "ok: spatial proof validator"
node "$repo_root/wp-expert/scripts/capture-spatial-measurements.mjs" --self-test
echo "ok: spatial measurement capture"

symlink_dir="$(mktemp -d)"
trap 'rm -rf "$symlink_dir"' EXIT
ln -s "$repo_root/wp-expert/scripts/validate-spatial-proof.mjs" "$symlink_dir/validate-spatial-proof.mjs"
ln -s "$repo_root/wp-expert/scripts/capture-spatial-measurements.mjs" "$symlink_dir/capture-spatial-measurements.mjs"
ln -s "$repo_root/wp-expert/scripts/validate-visual-proof.mjs" "$symlink_dir/validate-visual-proof.mjs"
ln -s "$repo_root/wp-expert/scripts/validate-asset-production.mjs" "$symlink_dir/validate-asset-production.mjs"
if node "$symlink_dir/validate-spatial-proof.mjs" --example | grep -Fq '"proofId"'; then
  echo "ok: symlinked spatial proof CLI"
else
  echo "ERROR: symlinked spatial proof CLI did not execute" >&2
  errors=$((errors + 1))
fi
if node "$symlink_dir/capture-spatial-measurements.mjs" --self-test | grep -Fq "capture self-test passed"; then
  echo "ok: symlinked spatial capture CLI"
else
  echo "ERROR: symlinked spatial capture CLI did not execute" >&2
  errors=$((errors + 1))
fi
if node "$symlink_dir/validate-visual-proof.mjs" --example | grep -Fq '"proofId"'; then
  echo "ok: symlinked visual proof CLI"
else
  echo "ERROR: symlinked visual proof CLI did not execute" >&2
  errors=$((errors + 1))
fi
if node "$symlink_dir/validate-asset-production.mjs" --example | grep -Fq '"assetId"'; then
  echo "ok: symlinked asset production CLI"
else
  echo "ERROR: symlinked asset production CLI did not execute" >&2
  errors=$((errors + 1))
fi
rm -rf "$symlink_dir"
trap - EXIT

if [ "$errors" -gt 0 ]; then
  echo "visual WordPress behavior audit failed: $errors issue(s)" >&2
  exit 1
fi

echo "visual WordPress behavior audit passed"
